title:              "DP7 Network"
type:               "normal"
navbar_title:       "DP7 Network Community"
email:              "la@dp7.link"
description:        "A warm & friendly community"
author:             "DP7 Network"
copyright:          "DP7 Network Community"
baseurl:            ""
url:                "https://dp-7-homepage.vercel.app"

license: '<a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>'

menu:
  - name: "Home"
    url: '/'
  - name: "About"
    url: '/about'
  - name: "Join Us"
    url: '/#加入我们'

# Social Profiles
#twitter_username:   ""
github_username:    "DP7-Network"
#facebook_username:  ""
#instagram_username: ""
#linkedin_username:  ""

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           6
paginate_path:      "/p:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
