# Site Settings
title: "DP7 Network"
description: "A friendly & warm network community"
baseurl: DP7-Homepage
url: https://dp7-network.github.io
encoding: UTF-8

# Build Settings
markdown: kramdown
permalink: pretty

# Jekyll Redirect From Plugin for Redirects from Start Bootstrap Old Version
gems:
  - jekyll-redirect-from